{"name": "Проверка невозможности создания двух одинаковых курьеров", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидаемый код: 409, полученный код: 409, ожидаемый текст: \"Этот логин уже используется\",             полученный текст: Этот логин уже используется. Попробуйте другой.\nassert (409 == 409 and 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\n  \n  - Этот логин уже используется. Попробуйте другой.\n  + Этот логин уже используется)", "trace": "self = <tests.test_courier_create.TestCourierCreate object at 0x000002B8FE0094F0>\ngenerate_courier_data_and_delete_after_test = {'firstName': 'Tara', 'login': 'barkeralexandra', 'password': 'v2o2KqbwW('}\n\n    @allure.title('Проверка невозможности создания двух одинаковых курьеров')\n    @allure.description('Создаем курьера, создаем еще одного курьера с теми же данными, \\\n                        проверяем, что код ответа: 409, текст ответа: \"Этот логин уже используется\"')\n    def test_create_two_same_couriers_fail(self, generate_courier_data_and_delete_after_test):\n        requests.post(f'{Data.main_url}/api/v1/courier', data=generate_courier_data_and_delete_after_test)\n        response = requests.post(f'{Data.main_url}/api/v1/courier', data=generate_courier_data_and_delete_after_test)\n        r = response.json()\n>       assert 409 == r['code'] and \"Этот логин уже используется\" == r['message'], \\\n            f'Ожидаемый код: 409, полученный код: {r['code']}, ожидаемый текст: \"Этот логин уже используется\", \\\n            полученный текст: {r['message']}'\nE       AssertionError: Ожидаемый код: 409, полученный код: 409, ожидаемый текст: \"Этот логин уже используется\",             полученный текст: Этот логин уже используется. Попробуйте другой.\nE       assert (409 == 409 and 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\nE         \nE         - Этот логин уже используется. Попробуйте другой.\nE         + Этот логин уже используется)\n\ntests\\test_courier_create.py:23: AssertionError"}, "description": "Создаем курьера, создаем еще одного курьера с теми же данными,                         проверяем, что код ответа: 409, текст ответа: \"Этот логин уже используется\"", "start": 1710001596347, "stop": 1710001596910, "uuid": "d5cc65bb-bb8c-4e01-85d9-3a2541762127", "historyId": "87c1c7131fb5b365052c3b3f88f546a2", "testCaseId": "87c1c7131fb5b365052c3b3f88f546a2", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_two_same_couriers_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "DESKTOP-1VNC7DB"}, {"name": "thread", "value": "34604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}